input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if [level] {
    mutate {
      uppercase => ["level"]
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "auth-service-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}